ch1/accounts/urls.py
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', auth_views.logout, name='logout',
        kwargs={'next_page': settings.LOGIN_URL}),
    url(r'^profile/$', views.profile, name="profile"),
]

ch1/mysite/urls.py
from django.contrib import admin
from django.conf.urls import url, include

# 미디어 설정
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns




urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^travel/', include('travel.urls', namespace='travel')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
]




# 미디어 업로드
# 어떤 URL을 정적으로 추가할래? > MEDIA_URL을 static 파일 경로로 추가
# 실제 파일은 어디에 있는데? > MEDIA_ROOT 경로내의 파일을 static 파일로 설정

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ch1/travel/urls.py
from django.conf.urls import url
from . import views




urlpatterns =[
    url(r'^$', views.main, name='main'),
    url(r'^local/$', views.local_list, name="local_list"),
    url(r'^local/(?P<local>\w+)/$', views.local_detail, name="local_detail"),
    url(r'^local/(?P<local>\w+)/(?P<name>\w+)/$', views.local_detail_form, name='local_detail_form'),
    url(r'^new/$', views.post_new, name="post_new")
]

ch1/accounts/models.py
from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models



class Profile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    phone_number = models.CharField(max_length=20, validators=[RegexValidator(r'^010[1-9]\d{7}$')])

ch1/travel/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse




class Category(models.Model):
    local_category = models.CharField(max_length=10)
    local_img = models.ImageField(default='null', upload_to='local_img')

    def __str__(self):
        return self.local_category

class Post(models.Model):
    title = models.CharField(max_length=60, default='')
    price = models.CharField(max_length=30, default='')
    time = models.CharField(max_length=10, default='')
    img = models.ImageField(upload_to='user_img', default='local_img/logo2.png')
    local = models.ForeignKey(Category)
    name = models.CharField(max_length=20)
    language = models.CharField(max_length=20)
    visited_country = models.CharField(max_length=20)
    next_country = models.CharField(max_length=30, default='ch')
    interest = models.CharField(max_length=60)
    content = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    guide_at = models.DateTimeField(default=timezone.now)
    email = models.EmailField(default="jyg0172@naver.com")


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('travel:local_detail_form', args=[self.local, self.name])

ch1/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.contrib.auth.forms import AuthenticationForm


class SignupForm(UserCreationForm):
    phone_number = forms.CharField()
    def save(self):
        user = super().save()
        profile = Profile.objects.create(user=user, phone_number=self.cleaned_data['phone_number'])
        return user

class LoginForm(AuthenticationForm):
    answer = forms.IntegerField(label='3+3=?')
    def clean_answer(self):
        if self.cleaned_data.get('answer', None) != 6:
            raise forms.ValidationError('땡~!!!')

ch1/travel/forms.py
from .models import Post
from django import forms



class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = {
            'name',
            'title',
            'content',
            'language',
            'visited_country',
            'next_country',
            'guide_at',
            'email',
            'interest',
            'img',
            'time',
            'price',
            'local'
        }

    def save(self, commit=True):
        post = Post(**self.cleaned_data)
        if commit:
            post.save()
        return post

ch1/accounts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from django.contrib.auth.views import login as auth_login
from allauth.socialaccount.models import SocialApp
from allauth.socialaccount.templatetags.socialaccount import get_providers
from .forms import LoginForm, SignupForm


def signup(request):
    if request.method =='POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect(settings.LOGIN_URL)
        else:
            form = SignupForm()
        return render(request, 'accounts/signup_form.html',{
            'form':form,
        })

def profile(request):
    return render(request, 'accounts/profile.html')



def login(request):
    providers = []
    for provider in get_providers():     # settings/INSTALLED_APPS 내에서 활성화된 목록
        # social_app속성은 provider에는 없는 속성입니다.
        try:
            # 실제 Provider 별 Client id/secret 이 등록이 되어있는가?
            provider.social_app = SocialApp.objects.get(provider=provider.id, sites=settings.SITE_ID)
        except SocialApp.DoesNotExist:
            provider.social_app = None
        providers.append(provider)

    return auth_login(request,
        authentication_form=LoginForm,
        template_name='accounts/login_form.html',
        extra_context={'providers': providers})

ch1/travel/views.py
from django.shortcuts import render, redirect
from .models import Category, Post
from .forms import PostForm


def main(request):
    return render(request, 'travel/_main.html')

def local_list(request):
    queryset = Category.objects.all()

    queryset1 = Post.objects.all()


    return render(request, 'travel/local_list.html', {
        'local' : queryset,
        'local_list' : queryset1
    })

def local_detail(request, local):
    queryset1 = Category.objects.all()
    queryset = Post.objects.all()
    path = request.path
    print(path)
    filter = path.split('/')[3]
    print(filter)
    qs = queryset.filter(local__local_category=filter)

    return render(request, 'travel/local_detail.html',{
        'local_list': qs
    })


def local_detail_form(request, local ,name):
    queryset = Post.objects.all()
    path = request.path
    print(path)
    filter = path.split('/')[4]
    print(filter)
    qs = queryset.filter(name=filter)
    return render(request, 'travel/local_detail_form.html',{
        'local_detail': qs,
        'filter':filter,
    })



def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            return redirect(post)
    else:
        form = PostForm()
    return render(request, 'travel/post_form.html', {
        'form': form,
})

ch1/accounts/templates/accounts/login_form.html
{% extends "base.html" %}

{% block content %}
{% load socialaccount %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" />
</form>
<h3>Social Login</h3>
<ul>
    {% for provider in providers %}
        <li>
            {% if provider.social_app %}
                <a href="{% provider_login_url provider.id %}">
                    {{ provider.name }}
                </a>
            {% else %}
                <a>
                    Provider {{ provider.name }} 설정이 필요합니다.
                </a>
            {% endif %}
        </li>
    {% endfor %}
 </ul>
 {% endblock %}

ch1/accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<h1>{{ user }}'s Profile</h1>
<ul>
    <li>email : {{ user.email }}</li>
    <li>name : {{ user.name }}</li>
    <li>date_joined : {{ user.date_joined }}</li>
</ul>
<img src="{{ user.socialaccount_set.all.first.get_avatar_url }}" />

<a href="{% url 'travel:post_new' %}"><h2>가이드로 등록하기</h2> </a>

{% endblock %}

ch1/mysite/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <style>
            *{
                margin: 0;
            }
            header{
                background-color: rgb(15,58,114);
                border-bottom: 1px solid black;
            }
            header #hdiv {
                width: 80%;
                margin: 0 auto;
                line-height: 60px;
            }
            header img{
                vertical-align: middle;
            }
            header #hdiv ul{
                float: right;
                vertical-align: middle;
            }
            header #hdiv ul li{
                display: inline-block;
                margin-left: 30px;
            }
            header #hdiv a{
                display: inline-block;
                font-size: 18px;
                text-decoration: none;
                color: white;
            }
            article{
                clear:both;
            }
            footer{
                clear: both;
                background-color: rgb(15,58,114);
            }
            footer #fdiv{
                width:68%;
                margin: 0 auto;
                padding-top: 50px;
            }
            footer #fdiv #wrap{
                display: flex;
                padding-bottom: 10px;
            }
            footer #fdiv .fdiv{
                margin-right: 120px;
            }
            footer #fdiv .fdiv li{
                list-style: none;
                color: white;
                margin-top: 20px;
            }
            footer #fdiv #ffdiv{
                padding:0px 30px 10px 30px;
            }
            footer #fdiv #ffdiv p{
                padding: 20px 0; font-size:14px;
                color: gray;
            }
            footer #fdiv #wrap .fdiv a{
                color: white;
                text-decoration: none;
            }    
        </style>
        <link rel="stylesheet"
        href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    </head>
    <body>
        <header>
            <div id="hdiv">
                {% load static %}
                <a href="{% url 'travel:main' %}"><img src="{% static 'img/logo.png' %}" width="190px" height="30px"></a>
                <ul>
                    <li><a href="#">Language</a></li>
                    <li><a href="{% url 'travel:local_list' %}">Tour</a></li>
                    <li><a href="#">Personalized</a></li>
                    <li><a href="#">Become a guide</a></li>
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                </ul>
            </div>
        </header>
        {% block content %}
        {% endblock %}
    </body>
</html>

ch1/mysite/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>1111</h1>
{% endblock %}

ch1/travel/templates/travel/_main.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<video poster="http://placehold.it/640x360" width="100%" height="100%" controls="controls">
    <source src="{% static 'video/video.mp4' %}" type="video/mp4" />
</video>

<article>
    <div style="margin:0 36%;">
        <a href="{% url 'travel:local_list' %}"/><img src="{% static 'img/img2.png' %}"></a>
    </div>
</article>

{% endblock %}

ch1/travel/templates/travel/local_deatail_form.html
{% extends "base.html" %}

{% block content %}
{% for i in local_deatil %}

<div>title : {{ i.title }}<br>name: {{i.name}}<br>price : {{ i.price }}<br>time : {{ i.time }}<br> Tour Local : {{ i.local }} <br>Enable Language : {{ i.language }}<br>Visited_country : {{ i.visited_country }} <br>Next_country : {{ i.next_country }}<br>Interest : {{i.interest}} <br> Content : {{ i.contet }}<br> Guide at: {{i.guide_at}}<br>Email : {{i.email }}<br><a href="#">APPLY</a>
</div>

<a href="#">APPLY</a>
{% endblock %}

ch1/travel/templates/travel/local_detail.html
{% extends "base.html" %}

{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for i in local_list %}
    <div style="border:1px solid black">
    <ul>
        <div style="border:1px solid black; width:30%; height:30%;">
        <li><a href="{{ i.name }}" style="text-decoration: none;"><h2>"{{ i.title }}"</h2></a><br>{{ i.price }} <br> {{ i.time }}<br>Enable Language : {{ i.language }}<br>visited Country : {{ i.visited_country }}<br>Interset : {{ i.interest }}<br></li>
        </div>
    </ul>
    </div>
    {% endfor %}
</body>
</html>

{% endblock %}

ch1/travel/templates/travel/local_detail_form.html
{% extends "base.html" %}

{% block content %}
{% for i in local_detail %}


<div>title : {{ i.title }}<br>name: {{i.name}}<br>price : {{ i.price }}<br>time : {{ i.time }}<br> Tour Local : {{ i.local }} <br>Enable Language : {{ i.language }}<br>Visited_country : {{ i.visited_country }} <br>Next_country : {{ i.next_country }}<br>Interest : {{i.interest}} <br> Content : {{ i.contet }}<br> Guide at: {{i.guide_at}}<br>Email : {{i.email }}</div>
<a href="#"><h1>APPLY</h1></a>

{% endfor %}
{% endblock %}

ch1/travel/templates/travel/local_list.html
{% extends "base.html" %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for i in local %}
    <ul>
        <div style="border:1px solid black; width:30%;">
        <!--미디어 불러오기 미치는줄 알았다...-->
        <li><h3>{{ i }}</h3><br><a href="{{ i.local_category }}"><img src="{{ i.local_img.url }}"/></a></li>
        </div>
    </ul>
    {% endfor %}
</body>
</html>

{% endblock %}

ch1/travel/templates/travel/post_form.html
{% extends 'base.html' %}



{% block content %}

<link rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<form method="post" action="">
    <legend>Post Form</legend>
    {% csrf_token %}
    <table class="table table-bordered table-hover">
        {{ form.as_table }}
</table>
    <input type="submit" class="btn btn-primary btn-lg" />
</form>
<script>
/* ??????? user_agent ??? ???? */
var dom = document.getElementById('{{ form.user_agent.id_for_label }}'); dom.value = navigator.userAgent;
</script>

{% endblock %}